### ISSUE TITLE
API issue?

### ISSUE THREAD

**Issue by Robskan5300** [discord/avatar-remix-bot#8]
No idea if this is fixable, but it keeps giving me this when I type "make it smile", given as an example in the source.
![Image](https://user-images.githubusercontent.com/100348563/224383023-1c496c72-e553-4b55-83c4-b62133739613.png)

Not sure, but this may also of course be a problem of workers.dev

**Comment by JustinBeckwith** [comment]
Yeah I'm not sure if there's much we can do on the actual underlying API itself :) @zeke?

**Comment by AshtakaOOf** [comment]
That's just what happens when you use an image with low contrast, like this blurple cat with Stable Diffusion and InstructPix2Pix.
This could be solved with ControlNet which is an alternative to Pix2Pix, it could also be solved by using a non blurple cat profile picture (or potentially by [Muse](https://github.com/lucidrains/muse-maskgit-pytorch) which is not finished yet).
Hope this help :)

**Comment by zeke** [comment]
Seems like a good opportunity to fork the repo and play with the Replicate model inputs, or try out different models entirely!
